// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UdrugeApp.DataAccess.SqlServer.Data.DbModels
{
    public partial class PotrosniResursi
    {
        [Key]
        public int IdResursa { get; set; }
        [Column(TypeName = "date")]
        public DateTime RokTrajanja { get; set; }

        [ForeignKey("IdResursa")]
        [InverseProperty("PotrosniResursi")]
        public virtual Resursi IdResursaNavigation { get; set; }
    }
}