// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UdrugeApp.DataAccess.SqlServer.Data.DbModels
{
    public partial class Resursi
    {
        [Key]
        public int IdResursa { get; set; }
        public int IdUdruge { get; set; }
        public int IdProstor { get; set; }
        public int InvertarniBroj { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Naziv { get; set; }
        [Column(TypeName = "date")]
        public DateTime DatumNabave { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Napomena { get; set; }

        [ForeignKey("IdProstor")]
        [InverseProperty("Resursi")]
        public virtual Prostori IdProstorNavigation { get; set; }
        [ForeignKey("IdUdruge")]
        [InverseProperty("Resursi")]
        public virtual Udruge IdUdrugeNavigation { get; set; }
        [InverseProperty("IdResursaNavigation")]
        public virtual PotrosniResursi PotrosniResursi { get; set; }
        [InverseProperty("IdResursaNavigation")]
        public virtual TrajniResursi TrajniResursi { get; set; }
    }
}