// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UdrugeWebApi.Data.DbModels
{
    public partial class TrajniResursi
    {
        [Key]
        public int IdResursa { get; set; }
        [Required]
        [StringLength(6)]
        [Unicode(false)]
        public string InventarniBroj { get; set; }
        public bool JeDostupno { get; set; }

        [ForeignKey("IdResursa")]
        [InverseProperty("TrajniResursi")]
        public virtual Resursi IdResursaNavigation { get; set; }
    }
}