// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UdrugeApp.DataAccess.SqlServer.Data.DbModels
{
    public partial class VoditeljiUdruge
    {
        [Key]
        public int IdUdruge { get; set; }
        [Key]
        public int IdClan { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Pozicija { get; set; }
        [Column(TypeName = "date")]
        public DateTime? NaPozicijiDo { get; set; }

        [ForeignKey("IdUdruge")]
        [InverseProperty("VoditeljiUdruge")]
        public virtual Udruge IdUdrugeNavigation { get; set; }
        public int Id { get; set; }
    }
}